
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-app
  name: jenkins-secret-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-secret-access
  namespace: dev-app
subjects:
  - kind: ServiceAccount
    name: jenkins-sa # Fixed to match the ServiceAccount
    namespace: jenkins-ns
roleRef:
  kind: Role
  name: jenkins-secret-manager
  apiGroup: rbac.authorization.k8s.io
  
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins-ns
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: jenkins-ns
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "secrets"]
    verbs: ["create", "delete", "get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: jenkins-ns
subjects:
  - kind: ServiceAccount
    name: jenkins-sa   # Fixed to match the ServiceAccount
    namespace: jenkins-ns
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sa-token
  namespace: jenkins-ns
  annotations:
    kubernetes.io/service-account.name: "jenkins-sa" # Links to your service account
type: kubernetes.io/service-account-token
